### ISSUE TITLE
Province metadata missing from municipalities

### ISSUE THREAD

**Issue by wldevries** [bmesuere/belgium-topojson#8]
The readme states that municipalities should include `prov_nis`, `prov_nl` and `prov_fr`, but they seem to be missing.
```
"properties": {
    "reg_nis": "04000",
    "reg_nl": "Brussels Hoofdstedelijk Gewest",
    "reg_fr": "Région de Bruxelles-Capitale",
    "nis": "21001",
    "name_fr": "Anderlecht",
    "name_nl": "Anderlecht",
    "arr_nis": "21000",
    "arr_fr": "Arrondissement de Bruxelles-Capitale",
    "arr_nl": "Arrondissement Brussel Hoofdstad",
    "population": 120887
}
```

**Comment by bmesuere** [comment]
Are they missing for all muni's (I'm on my phone so I can't check myself)? Because the example you picked is from Brussels and although it sounds strange, these municipalities are in fact not part of a province.

**Comment by wldevries** [comment]
You are right! I had no idea, things are simpler in the Netherlands :-)
